### ISSUE TITLE
Capitalisation affects translation?

### ISSUE THREAD

**Issue by fortunewalla** [AI4Bharat/IndicTrans2#1]
`She is at home` --> ಆಕೆ ಮನೆಯಲ್ಲೇ ಇದ್ದಾಳೆ.
vs.

`she is at home` --> ಅವಳು ಮನೆಯಲ್ಲಿದ್ದಾಳೆ

### She is at home
![image](https://github.com/AI4Bharat/IndicTrans2/assets/7158596/53ee9240-0452-44d0-b991-3212864807c1)

### she is at home
![image](https://github.com/AI4Bharat/IndicTrans2/assets/7158596/d9864832-3070-477e-81fe-8f3e2ea7e7af)

**Comment by jaygala24** [comment]
Thank you for bringing up this issue. We acknowledge that there can be slight variations in translations due to the sensitivity to case and punctuation. Currently, the demo hosts the initial versions of our IndicTrans2 models, and our objective is to improve these models based on user feedback.

We value your participation and encourage you to try more such examples and provide your feedback directly on the demo platform itself. Your feedback will play a vital role in improving the translation quality of our models. Thank you!
