### ISSUE TITLE
Non Kashmiri Character

### ISSUE THREAD

**Issue by Iflaq12** [AI4Bharat/IndicTrans2#11]
The model introduces a non Kashmiri Character in translations.
There are multiple instances where "ٮ۪" is introduced as in "پٮ۪ٹھ" characters are in the output, but they are non Kashmiri.
The correct spelling is "پؠٹھ"
There shape of the lower character is not rectangular in Kashmiri but circular.

**Comment by PranjalChitale** [comment]
Hi @Iflaq12 , possibly this might have occurred due to some interferences due to the presence of high-resource languages in the same script.

As we detail in the limitations section of our paper, although performance on low-resource languages has improved over the previous approaches, there is still room for improvement to ensure that such issues can be minimized.

Thank you for your feedback, we will surely work on it and try to continually improve our models in the future.
