### ISSUE TITLE
 Translations from a Female Perspective.  (Reopening the issue #92)

### ISSUE THREAD

**Issue by Sab8605** [AI4Bharat/IndicTrans2#97]
As discussed in issue #92, could you please provide a bit more detail about the decoding algorithm?

I have tested an approach to address this issue by prefixing each sentence with "She said: I am walking on the road." This results in translations like "उसने कहाः मैं सड़क पर चल रही हूँ।" I then extract the text following "उसने कहाः " to get the actual translation. Most of the time, the translation correctly follows this prefix. However, I’ve noticed some variations where the translation starts with ["उन्होंने कहा,","उन्होंने कहा","उसने कहा,","उसने कहा"]. Despite these variations, the results generally align with the female perspective.

Or is there a potential issue with this approach, or could another solution be more suitable?

**Comment by PranjalChitale** [comment]
Yes, the approach you suggest is reasonable. 

To further safeguard against issues with postprocessing due to variations in the prefix translation, I would suggest the following:

1. Append a unique delimiter after the prefix in your input (e.g., "he said {delimiter} {sentence}" or "she said {delimiter} {sentence}"). The delimiter could be something like "---" or "###". You may need to experiment with different delimiters to find which works best in practice.
2. After obtaining the translation, split the result based on the delimiter.
3.  For Perso-Arabic languages, take the first chunk after the split. For other languages, use the second chunk.

This method helps ensure that any variability in prefix translation does not disrupt your postprocessing steps.

**Comment by Sab8605** [comment]
Thanks for quick solution, 

Is there any approach can you suggest on decoding algorithm for this issue?

**Comment by PranjalChitale** [comment]
https://aclanthology.org/2022.findings-acl.301/

The above work may be relevant.
